"""
Graph State Definition
Uses TypedDict + Annotated to manage the global state structure of LangGraph.
The messages field uses operator.add to enable cross-node/cross-turn message accumulation
(automatically persisted as STM by Checkpoint).
"""
import operator
from typing import TypedDict, Annotated, List, Dict, Any


class AgentState(TypedDict):
    # =====================================================================
    # Short Term Memory (STM)
    # Automatically managed by LangGraph Checkpoint; accumulates across turns
    # within the same thread_id.
    # operator.add ensures new messages returned by each node are appended
    # to the existing message list.
    # =====================================================================
    messages: Annotated[list, operator.add]

    # =====================================================================
    # User identifier — used to index LTM and KG external persistent storage
    # =====================================================================
    user_id: str

    # =====================================================================
    # Long Term Memory (LTM) — list of facts retrieved from MemoryStore
    # Refreshed each turn by the retrieve_ltm node; non-cumulative (overwrite)
    # =====================================================================
    long_term_memory: List[str]

    # =====================================================================
    # Knowledge Graph Context — currently valid information retrieved from TemporalKG
    # Refreshed each turn by the retrieve_kg node; non-cumulative (overwrite)
    # =====================================================================
    kg_context: List[str]

    # =====================================================================
    # Query Rewriter output — rewritten query after fusing LTM/KG/STM
    # Used by tool_retriever to improve tool retrieval accuracy
    # =====================================================================
    contextualized_query: str

    # =====================================================================
    # Final response text generated by Generator
    # =====================================================================
    response: str
